name: Generate Vault Index

on:
  push:
    branches:
      - main  # or 'master' if that's your default branch

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # 1. Checkout repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Run index generation script
      - name: Generate README indexes
        run: python generate_index.py

      # 4. Auto-commit changes to .md files (if any)
      - name: Commit README updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-generate vault index"
          file_pattern: "**/*.md"
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
